export const gameCategories = [
    {"id": 1, "game_name": "GTA V"},
    {"id": 2, "game_name": "RDR 2"},
    {"id": 3, "game_name": "Witcher 3"},
    {"id": 4, "game_name": "Horizon Zero Dawn"},
    {"id": 5, "game_name": "Horizon Forbidden West"},
    {"id": 6, "game_name": "Assassin's Creed Origins"},
    {"id": 7, "game_name": "Assassin's Creed Valhalla"},
    {"id": 8, "game_name": "Hitman 3"},
    {"id": 9, "game_name": "Cyberpunk 2077"},
    {"id": 10, "game_name": "Elden Ring"},
    {"id": 11, "game_name": "God of War"},
    {"id": 12, "game_name": "Ghost of Tsushima"},
    {"id": 13, "game_name": "The Last of Us Part II"},
    {"id": 14, "game_name": "Death Stranding"},
    {"id": 15, "game_name": "Resident Evil Village"},
    {"id": 16, "game_name": "Marvel's Spider-Man"},
    {"id": 17, "game_name": "Doom Eternal"},
    {"id": 18, "game_name": "Far Cry 6"},
    {"id": 19, "game_name": "Mass Effect Legendary Edition"},
    {"id": 20, "game_name": "Star Wars Jedi: Fallen Order"},
    {"id": 21, "game_name": "Control"},
    {"id": 22, "game_name": "Sekiro: Shadows Die Twice"},
    {"id": 23, "game_name": "Borderlands 3"},
    {"id": 24, "game_name": "Days Gone"},
    {"id": 25, "game_name": "Watch Dogs: Legion"},
    {"id": 26, "game_name": "Metro Exodus"},
    {"id": 27, "game_name": "Dying Light 2"},
    {"id": 28, "game_name": "Mortal Kombat 11"},
    {"id": 29, "game_name": "Red Dead Redemption"},
    {"id": 30, "game_name": "FIFA 22"}
  ];
